#!/usr/bin/env python3
"""Sync all public GitHub repos from both accounts into src/data/projects.ts.

Usage:  python3 scripts/sync-repos.py
Re-run anytime to pick up new repos or updated descriptions.
"""
import base64
import datetime
import json
import re
import urllib.request
from pathlib import Path

USERS = ["amitb-gpu", "amitb-quantum"]
# Repos that are infrastructure for the site itself, not showcase projects.
EXCLUDED = {"amit-brahmbhatt.dev"}
# A repo pushed within this many days counts as "active" (unless archived).
ACTIVE_DAYS = 180

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "data" / "projects.ts"
OVERRIDES = ROOT / "src" / "data" / "descriptions.override.json"
# Curated area mapping, keyed "org/repo" -> ai-gpu | trustworthy | quantum | other.
AREAS_FILE = ROOT / "src" / "data" / "areas.override.json"


def load_overrides():
    """Curated descriptions, keyed by 'org/repo'. Preferred over GitHub
    descriptions so hand-written copy survives re-syncs."""
    if OVERRIDES.exists():
        return json.loads(OVERRIDES.read_text())
    return {}


def repo_status(r):
    """active = pushed within ACTIVE_DAYS, archived = GitHub archived flag,
    otherwise quiet. Derived from repo metadata, not curated."""
    if r.get("archived"):
        return "archived"
    pushed = (r.get("pushed_at") or "")[:10]
    try:
        days = (datetime.date.today() - datetime.date.fromisoformat(pushed)).days
        return "active" if days <= ACTIVE_DAYS else "quiet"
    except ValueError:
        return "quiet"


def api(path):
    req = urllib.request.Request(
        f"https://api.github.com{path}",
        headers={
            "User-Agent": "amit-site-sync",
            "Accept": "application/vnd.github+json",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def readme_first_line(owner, repo):
    """First meaningful line of the README, for repos with no description."""
    try:
        data = api(f"/repos/{owner}/{repo}/readme")
        text = base64.b64decode(data["content"]).decode("utf-8", "replace")
        for line in text.splitlines():
            s = line.strip()
            if not s or s.startswith(("#", "![", "[![", "<", "|", "-", "* ")):
                continue
            s = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", s)  # [text](url) -> text
            s = re.sub(r"[*_`>]", "", s).strip()
            if len(s) > 25:
                return s[:220]
    except Exception:
        pass
    return ""


def ts_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    overrides = load_overrides()
    areas = json.loads(AREAS_FILE.read_text()) if AREAS_FILE.exists() else {}
    entries = []
    for user in USERS:
        repos = api(f"/users/{user}/repos?per_page=100&type=public&sort=updated")
        for r in repos:
            if r.get("fork"):
                continue
            if r["name"] in EXCLUDED:
                continue
            key = f"{user}/{r['name']}"
            desc = overrides.get(key, "").strip()
            if not desc:
                desc = (r.get("description") or "").strip()
            if not desc:
                desc = readme_first_line(user, r["name"])
            if not desc:
                desc = "No description yet — see the repo for details."
            tags = [t for t in (r.get("topics") or [])[:3]]
            if r.get("language") and len(tags) < 4:
                tags.append(r["language"])
            area = areas.get(key, "other")
            status = repo_status(r)
            tags_ts = ", ".join(f'"{ts_escape(t)}"' for t in tags)
            entries.append(
                f'  {{\n'
                f'    name: "{ts_escape(r["name"])}",\n'
                f'    description: "{ts_escape(desc)}",\n'
                f'    url: "{r["html_url"]}",\n'
                f'    tags: [{tags_ts}],\n'
                f'    org: "{user}",\n'
                f'    area: "{area}",\n'
                f'    status: "{status}",\n'
                f'  }},'
            )

    body = "\n".join(entries)
    OUT.write_text(
        """export interface Project {
  name: string;
  description: string;
  url: string;
  tags: string[];
  org: "amitb-gpu" | "amitb-quantum";
  area: "ai-gpu" | "trustworthy" | "quantum" | "other";
  status: "active" | "quiet" | "archived";
}

// Auto-generated by scripts/sync-repos.py — re-run to sync with GitHub.
// Curated descriptions live in src/data/descriptions.override.json and win over GitHub.
// Curated area mapping lives in src/data/areas.override.json (default: "other").
// Status is derived from GitHub metadata: archived flag, else pushed within
// 180 days = active, otherwise quiet.
export const projects: Project[] = [
"""
        + body
        + "\n];\n"
    )
    print(f"Wrote {len(entries)} repos to {OUT}")


if __name__ == "__main__":
    main()
